name: ci

on:
  push:
    branches:
    - master
    tags:
    - 'v*'
  pull_request:

env:
  GO_LATEST: "1.19"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-go@v4
      with:
        go-version: ${{env.GO_LATEST}}
    - uses: goreleaser/goreleaser-action@v4
      if: startsWith(github.ref , 'refs/tags/v') == false
      with:
        args: build --snapshot
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/upload-artifact@v3
      if: startsWith(github.ref , 'refs/tags/v') == false
      with:
        name: hcl2json
        path: dist/*
    - uses: goreleaser/goreleaser-action@v4
      if: startsWith(github.ref , 'refs/tags/v')
      with:
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
